### ISSUE TITLE
crash when a new player joins

### ISSUE THREAD

**Issue by shinrax2** [offyerrocker/PD2-AdvancedCrosshairs#2]
i was playing with randoms and whenever a new player joined midheist my game crashed

map: scarface mansion

<details>
<pre>
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                     vstdlib_s  (???)     CUniformRandomStream::`vftable'                     
                       DbgHelp  (???)     ExtensionApiVersion                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                       value()  @mods/PD2-AdvancedCrosshairs/lua/menumanager.lua:1835  
                     _notify()  lib/utils/messagesystem.lua:60                      
                      update()  lib/utils/messagesystem.lua:74                      
                    original()  lib/managers/playermanager.lua:591                  
                      update()  @mods/base/req/core/Hooks.lua:265                   
                    original()  lib/setups/setup.lua:868                            
                      update()  @mods/base/req/core/Hooks.lua:188                   
                      update()  lib/setups/gamesetup.lua:739                        
                      update()  lib/setups/networkgamesetup.lua:21                  
                    original()  core/lib/setups/coresetup.lua:557                   
                                @mods/base/req/core/Hooks.lua:265                   

-------------------------------

System information:
	Application version : 1.103.7
	CPU : AMD Ryzen 5 5600X 6-Core Processor (6 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 3070 / nvldumd.dll[27.21.14.6589]
	Language : german
	Memory :     32712MB 468KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Lautsprecher (Realtek(R) Audio))

</pre>
<summary> crashlog </summary>
</details>

**Comment by offyerrocker** [comment]
Which version of ACH are you using?

**Comment by shinrax2** [comment]
for whatever reason i was using version 5
updating to version 11 fixed it
