### ISSUE TITLE
I noticed that there is a Chinese translation of Simplified Chinese in ach, but it didn't work.

### ISSUE THREAD

**Issue by simonnar** [offyerrocker/PD2-AdvancedCrosshairs#3]
main.xml  should be written as <loc file="chinese.txt" language="schinese" /> Instead of chinese Then this Chinese file is really too old, I re-Chinese part of
[chinese.txt](https://github.com/offyerrocker/PD2-AdvancedCrosshairs/files/6875598/chinese.txt)

**Comment by offyerrocker** [comment]
Thanks very much for your contribution- I've applied your adjusted translations and fixed the language name in main.xml accordingly.
